### PR TITLE
Install the npm package from this repo

### PR DESCRIPTION
**Pull request by pedro**
makes development a bit easier

### CODE REVIEW

**Comment by talkol** [comment]
I was under the impression that limitations with the react native packager prevented it from locating packages outside the project root (example/ in our case). Was this fixed?

**Comment by pedro** [comment]
Ah, interesting! This works here with npm 3.8, maybe a limitation in 2?

Long story here: https://github.com/npm/npm/issues/1558

**Comment by talkol** [comment]
Yes, good point. So this would help in development so after making changes in the main repo, I would just `npm update` and the updated unpublished version will be copied to the example node_modules.

I get the benefit, but it's still not a perfect dev experience :) It would have been nicer to have a symbolic link to the parent folder from the node_modules folder but unfortunately the RN packager doesn't support that. Right now, I usually develop inside the node_modules folder and copy my changes manually one folder up when done.. sucks

Anyways, I think part of the purpose of the example is to show users how to use the package. So I think it's important to keep the package.json similar to what they're expected to have in their own projects

**Comment by pedro** [comment]
heh right on, I still symlink stuff into node_modules sometimes when doing heavy work.

but fair point, closing it then!

**Pull request closed without merging**
