### PR TITLE
Documentation grammar fix

### PR DESCRIPTION
**Pull request by jasonmerino**
Changed "has" to "had".

### CODE REVIEW

**Review by daedaesplayground — COMMENTED** [review]
Just let me know any changes that you guys feel that are I'm mediately necessary for me to make in the immediate future as well as any immediate security or copyright concerns that I should be aware of and please let me know so that I can implement necessary changes now.

**Comment by daedaesplayground** [comment]
I'm just totally in the dark about what to do on this issue.

**Comment by daedaesplayground** [comment]
Send me the best suggestions for what to do that you can think of.

**Comment by jasonmerino** [comment]
The only change here is switching out the word "had" for "has". 

"...although React Native for iOS has been out at the time for over a year."

to 

"...although React Native for iOS had been out at the time for over a year."

**Comment by DanielZlotin** [comment]
🤣

**Pull request closed without merging**
