### PR TITLE
Podspec

### PR DESCRIPTION
**Pull request by adamski**
Add Podspec and CocoaPods installation instructions

### CODE REVIEW

**Comment by artald** [comment]
@adamski thanks a lot for creating the podspec!
I have some minor changes I'd like to make in the file, please see [here](https://gist.github.com/artald/d5141598a9b81be21553).

I've also encountered an issue when running `pod spec lint` and `pod lib lint`. I'm getting errors related to React libraries. Can you look into it?

**Comment by adamski** [comment]
So I also had issues with `pod spec lint` - because the pod wont build without React, but you can't specify react React as a dependency because React is no longer in CocoaPods (the last version was 0.11) - they switched to only supporting installation via npm. Chicken and egg situation. However it all builds and works AFAICS. So I decided to ignore the lint failure, seeing as this Pod will likely only be installed via npm too. 

Hence my last PR which set the version to `0.0.1-master`, which is what React does now: https://github.com/facebook/react-native/blob/master/React.podspec
However I can't work out how they still get the actual (npm listed) version coming up when React is installed via `pod install`.

**Comment by artald** [comment]
I know that the last CocoaPods version of React is 0.11, and the errors indeed come from incompatible React versions. It's just that I was hoping there's some way to make the lint pass..

Not sure how setting the version to `0.0.1-master` can help us. I don't see other React podspec files use this, not even by Facebook like [this one](https://github.com/facebook/react-native-fbsdk/blob/master/react-native-fbsdkcore/react-native-fbsdkcore.podspec).

I want to make sure everything works properly before we publish to the specs repo. 
Is there a way to test it? Maybe we can create another example project which uses `react-native-controllers` as a pod directly from git to see that it works?

**Comment by adamski** [comment]
An example project sounds like a good idea. Not something I have time for right now unfortunately, but I'd be happy to help if I can. I guess a test project which builds without errors would be a way to go, e.g. with Travis-CI. 
Re: version number, I see - it was something I noticed in the recent React podspec and thought I would following their example.

**Comment by artald** [comment]
np.
I'll check what's the best way to test before we publish it.

**Comment by adamski** [comment]
OK so I checked out whats going in the RN repo with regards to auto-updating the Podspec version: https://github.com/facebook/react-native/blob/master/scripts/bump-oss-version.js#L49

This might be good to borrow for a build script here. That script auto updates versions across all dependency systems (npm, Gradle and Cocoapods).

**Comment by adamski** [comment]
I've reverted to storing the version number in the Podspec. Please consider merging this in. Thanks.

**Comment by drorbiran** [comment]
Hi, we wanted to update you that we are currently postponing the processing of pull requests.
Please refer to [React native controllers evolution](https://github.com/wix/react-native-controllers/issues/87), we'll appreciate your feedback.

**Comment by drorbiran** [comment]
Hi,
Thanks for the pull request.
We decided that we are not going to address Podspec and CocoaPods at this stage.

**Comment by lin-hun** [comment]
why????????
Its a terrible way to make dependence by 1..2...3..4 structions

**Pull request closed without merging**
